### ISSUE TITLE
LILYGO ESP32 doesn't show up as device despite drivers on MacBook with USC-C ports

### ISSUE THREAD

**Issue by JoshuaPerk** [scottbez1/splitflap#228]
Wanted to document an issue I'm troubleshooting. It's unrelated to this library so I don't expect community support but wanted the closed issue to potentially help future makers (once I diagnose the problem myself).

Despite installing a variety of drivers ([CH34XSER](https://learn.adafruit.com/how-to-install-drivers-for-wch-usb-to-serial-chips-ch9102f-ch9102/mac-driver-installation), [CH341SER](https://www.wch.cn/downloads/CH341SER_MAC_ZIP.html) — using both `.pkg` and `.DMG` files and manually adding Mac's Rosetta to support drivers with older architecture) I've been unable to get the ESP-32 to show up as a device.

I'm on 2021 MacBook Pro with an M1 Pro running Ventura 13.4. My machine _only_ has support for USB-C ports.

I _suspect_ this might be related to [some of the issues](https://www.reddit.com/r/esp32/comments/x7odev/esp32_devkit_usbc_boards_not_working_with_usbc/) folks have seen where they're unable to go directly from USC-C to USB-C.

I've attempted 3 different USC-C to USB-C cables (all of which support data and work when a device such as my iPhone are plugged into it).

I've also attempted to use 1 USB-A to USC-C cable that's plugged into a USB-C dongle (with multiple USB-A 3.0) ports (+ ethernet, HDMI, SD card, etc.). This also doesn't work, despite that same setup working if I plug my iPhone into it.

I placed an order for a new [USB-A to USB-C cable](https://www.amazon.com/gp/product/B0794M53HQ/ref=ppx_yo_dt_b_asin_title_o00_s01?ie=UTF8&th=1) with a [USB-A to USB-C dongle](https://www.amazon.com/gp/product/B07CVX3516/ref=ppx_yo_dt_b_asin_title_o00_s01?ie=UTF8&psc=1).

I'll update this (and close it) once I resolve it.

P.S. Received my hardware order from @scottbez1 and these boards are _beautiful_. Well done! 🔥

**Comment by JoshuaPerk** [comment]
Ah, interesting. I ordered 2x TTGO boards and one of them shows up just fine with a USB-C cable (totally negating my theory above).

I will try to diagnose why the first board is unresponsive on the port.

**Comment by JoshuaPerk** [comment]
Seems to be a bad USB chip - will probably just order a new one unless anyone knows how to reset the firmware without being a recognized device.

**Comment by scottbez1** [comment]
Unfortunately the Lilygo T-Display board has an error in their design, which can make it fail to enumerate correctly with a USB-C to C cable -- one of the 2 CC lines is not connected to the correct USB-C pin, and they are only using a single CC resistor.

This can make the USB-C connector directional, and sometimes may only work when the connector is plugged in one way and not the other :disappointed: 

If you've tried the USB-A to C plug, ideally with a USB 2.0 port rather than 3.0 port on your computer, and tried plugging the USB-C end into the T-Display both ways and it's still not enumerating (but the other T-Display works), **please send me a message on Etsy and I can process a refund/replacement for that one defective T-Display**.

For USB 2.0 on a type C connector, it's typical to connect 2 5.1k resistors, one to each of the CC1/CC2 pins, in order for the device to be detected and for it to receive power at 5V. The T-Display only has a single resistor, and they've connected it to A5 (which is correct) and also B8 (which is incorrect for 2 reasons - the second CC pin should not share a resistor, and the second CC pin is B5, not B8).

![image](https://github.com/scottbez1/splitflap/assets/414890/bc53f585-d9a9-4825-9c95-d02846c41618)


Any future revision to the controller portion of this project will definitely use a better module... The T-Display was one of the better modules for its time, but there are better options available for new designs today.

**Comment by JoshuaPerk** [comment]
@scottbez1 Here's my attempt at a (failed) clean install: https://video.drift.com/v/abkLtL8scZirYP9gRbX3qmaZcCwSctW1wcY6wbv5uwOzM/

**Comment by JoshuaPerk** [comment]
Resolved: https://video.drift.com/v/abwDzmH8Rqo8JmEof6nIEin00uRlwJB8WlQewGrAaFs/
Discord thread: https://discord.com/channels/521805668735385606/521806401807450115/1181404579502510130
