### ISSUE TITLE
IR sensor / Home position problem

### ISSUE THREAD

**Issue by daniele8808** [scottbez1/splitflap#33]
Hi Scott I've been reading the wiki and the instructions on the IMGUR websites but I still have some problems about the IR sensor. 

Here some picture of the mark for the home position and how I placed the sensor:

I tried in this two way to make the sensor recognize the mark on the gear
[Picture of the sensor](https://ibb.co/hJeLTU)
[Picture of the sensor2](https://ibb.co/gifG2p)

[First mark on the gear using a screw](https://ibb.co/fqMOhp)
[Second mark on the gear using black paint](https://ibb.co/mfMKsp)

They seems both of thems working, by now I'm using the second example with the black paint.

I place this mark close to the "D" letter but this is not what I wanted.
I have two question:

- Is there a way to set the home position by code or do I have to replace all the cards to make the home position to the letter I desire?
- Is there a way to test if the IR sensor is correctly working?

I also made a Video showing my problem when it is working.

If I type "@" the display seems work correctly because it spins until it reach the home position set to D letter but if then I type for example a letter which should be far from home position like "g", the display should spin for a while to reach the letter but it spin sometimes just 1 position and other time it spins again until home position. 
I really don't get it where is the problem.

Here the video -> [Video](https://youtu.be/9d1Rm2Y1zkU)

Any help would be really helpful.
I'm really close to finish my first module and I would like to make others for my project but by now I'm  stuck on this problem.

Thanks in advance for everithings.

**Comment by scottbez1** [comment]
>Is there a way to set the home position by code or do I have to replace all the cards to make the home position to the letter I desire?

While you _can_ update the code to adjust which letter is in the home position, I would generally recommend moving the cards so that the letter you want is in the home position. Though of course I would wait to do this until the IR sensor issue is resolved because you wouldn't want to have to do it twice 😛

The reason for that is that the Arduino code assumes all modules have the same home position, so it's _VERY_ convenient if all modules are physically configured so the letter you want is aligned with the sensor's home position. It would be possible to configure a separate offset for each module in the code, but then you'd always have to make sure you don't mix up which module is plugged into which ports or else the wrong offsets would be applied.

If you do want to adjust the home position (or really anything about how the flap order is defined in the code), you can do that by rearranging the items in the `flaps` array in the main sketch:

https://github.com/scottbez1/splitflap/blob/master/arduino/splitflap/splitflap.ino#L34

The "home" position is the first item in that array.

>Is there a way to test if the IR sensor is correctly working?

There are a few steps that I would take to debug this problem:
1. **Test the motor/mechanics in isolation:** I saw what looked like a few hesitations or possible missed steps in your video, so figured I'd suggest this as a starting point. I'd first disable the home position sensors entirely by setting `HOME_CALIBRATION_ENABLED` to `false` in `splitflap_module.h` -- the reason for this is that a flaky/broken sensor can cause all sorts of strange behavior. Then, use the Serial Monitor to tell the Arduino to go to the empty space (i.e. `= \n`) - check to make sure that the flaps turn smoothly, and remember what letter the module ends on. Do the same thing again and confirm that the module ends up on the same letter. Do this a few more times (at least 5) to make sure everything is working mechanically. If it doesn't return to the same letter and you've verified that there's nothing physically obstructing the spool from turning (e.g. sometimes flaps will get caught on the top/sides of the window), let me know and I can provide some additional troubleshooting steps.
2. **Test the sensor in isolation:** If you have a volt meter (or ideally an oscilloscope), connect it to the sensor's output pin while the sensor is plugged into the Arduino. The voltage should be near 0V (or at least lower than 3V) when the sensor is NOT aligned with the hole. Then manually rotate the flaps carefully until the hole is aligned with the IR sensor (on the design with gears I'd recommend rotating the motor gear rather than the spool itself). The voltage should increase to be near 5V. The change in voltage should be very obvious; if it's not, it suggests there's not enough contrast between the home position and everything else. If that's the case I would suggest cutting some white paper into a circle, making a black dot or line with a permanent marker, and then taping it to the gear's surface. If you don't have a voltmeter or oscilloscope, you can connect the sensor to an analog pin on the Arduino and check the voltage using a simple sketch that outputs the analog value over serial, though _you'll need to make sure to enable the internal pull-up if you do this_ (i.e. `pinMode(X, INPUT_PULLUP)`).

Hopefully one of those two steps is useful in tracking down the issue.

By the way, I noticed in your video the "count_missed_home" value increases when the display seems to have trouble, while the "count_unexpected_home" value remains at 0. When "count_missed_home" increases, that means the controller expected to find the home position (once per full revolution) but rotated past where it was expected and still didn't find it. When that occurs, the controller immediately enters calibration mode, where it rotates slowly to find the home position, and then once the home position is found it will rotate at full speed to the last requested letter. This generally happens if the motor got jammed up at some point and didn't rotate the correct amount, or else the sensor just didn't find the home position for some reason (e.g. it's not aligned with the hole correctly) -- this is why I've suggested the two troubleshooting steps above.

**Comment by scottbez1** [comment]
Hey @daniele8808, any luck tracking down the issue? Happy to continue helping if you're still running into issues, otherwise I'd like to go ahead and close this issue (I've added the troubleshooting steps from above to [the wiki](https://github.com/scottbez1/splitflap/wiki/Troubleshooting) since I'm certain you're not the only one who has run into issues like this).

**Comment by daniele8808** [comment]
Hi Scott I've been out for work until today.
I will try what you wrote this afternoon and update you soon. 
Thank you.

**Comment by scottbez1** [comment]
Closing this for now. Feel free to reopen if you're still having issues.
