### ISSUE TITLE
Split Flap Card, cut and stickers

### ISSUE THREAD

**Issue by l0l0l0** [scottbez1/splitflap#37]
Hello, 
Congratulations for your wonderful project !
I was wondering if it would not be easier to put the sticker before cutting the cards?

thanks

**Comment by scottbez1** [comment]
That could theoretically be done, but would only be possible for every second letter since flaps are double-sided, so I'm not sure it would help all that much?

By the way, I recently updated the wiki with a new recommended way of applying the letter stickers, which should be a lot quicker and more precise than the old method of cutting the stickers in half and applying one half at a time: https://github.com/scottbez1/splitflap/wiki/Apply-flap-stickers#new-instructions

**Comment by scottbez1** [comment]
Closing for now. Let me know if I've misunderstood or missed something.
