### ISSUE TITLE
Experimental electronics or 0.3 + hall effect sensor ?

### ISSUE THREAD

**Issue by henricazottes** [scottbez1/splitflap#46]
Hi,

Is the experimental driver pcb safe to use ? The old 0.3 version is quit old and I can see there is a 0.5 tag :p

Moreover I ordered hall effect sensors, may I use it with the 0.3 design ? (it was my guess but it would be great to confirm it )

So as of today which version should I use?

Thanks :)

**Comment by scottbez1** [comment]
The hall effect sensors and previous IR reflectance sensors both were set up with the same connector pinout (Signal, +5V, GND) so nothing has actually changed on the driver PCB related to the sensor input (the signal line is just connected to a shift register with 47k pull-up resistors). So both v0.3 and v0.5 driver PCBs will work with either IR sensors or hall effect.

As you noted, the updated driver PCB is part of the v0.5 release (https://github.com/scottbez1/splitflap/releases/tag/v0.5) from 2 days ago. The v0.5 design is stable and tested, and I would recommend it over v0.3 for the small reasons mentioned in the release notes.

The only thing you really need to worry about with the switch to hall effect sensors is to use the v0.5 mechanical design rather than v0.4 or else there won't be a great way to mount the sensor to the enclosure, and the hole on the spool will be bigger than the spec'ed 4mm magnets. But even then I'm sure it could be made to work 😛

Hope that helps!

**Comment by henricazottes** [comment]
Great, thanks for the detailed answer :)
