### ISSUE TITLE
Kicad 5

### ISSUE THREAD

**Issue by scottbez1** [scottbez1/splitflap#58]
The electronics projects are currently Kicad 4, but Kicad 5 is the latest version.

It would be nice to update all of the files to Kicad 5 and then verify that the schematics, footprints, and pcbs, along with all the Travis CI integration, still work correctly.

**Comment by whitebird** [comment]
I've opened up the sensor PCB in KiCad 5. When opening a 3D view it throws the following error;
<img width="532" alt="screenshot 2019-02-04 at 14 57 51" src="https://user-images.githubusercontent.com/1058174/52212677-62869e00-288d-11e9-915f-496826df5cc3.png">

This is probably due to the yellow lines from the Edge.cuts layer not being a closed square. Can this be for mass producing the piece? I don't have KiCad 4 to compare the issue.

<img width="740" alt="screenshot 2019-02-04 at 14 58 15" src="https://user-images.githubusercontent.com/1058174/52212687-66b2bb80-288d-11e9-8cb2-4418b5f837e7.png">

**Comment by scottbez1** [comment]
Yeah, those weird edge lines were from early experimentation with panelizing the board. IIRC the current panelization script ignores the original board outline layer entirely and redraws new lines based on the panelization parameters, but I'm not at my computer to double check at the moment. Regardless of the current behavior of the panelization script, the right thing to do is to fix that board outline, so I'll make a note to take care of that at some point.

**Comment by scottbez1** [comment]
Closing in favor of #138
