### ISSUE TITLE
 python file

### ISSUE THREAD

**Issue by carlosbritotx** [scottbez1/splitflap#71]
Hi friend, how do I use your python file? I'm starting the programming now.

**Comment by scottbez1** [comment]
Apologies for responding so late. The python scripts in the `software/` directory are intended to run on a computer connected to the Arduino controlling the splitflaps, and demonstrates how you can control the display via a serial port.

The `generate_acceleration.py` python script in the arduino directory can be used to re-generate the stepper motor acceleration curves in the arduino code - you don't need to worry about this at all for normal use, but if you need to tweak the top speed (e.g. due to motors stalling), you can do so here and then run the script which will update the Arduino code.

Closing this for now, please leave a comment or open a new issue if you still have questions, thanks!
