### ISSUE TITLE
Some questions about the code....

### ISSUE THREAD

**Issue by digitalkid2analogman** [scottbez1/splitflap#74]
I'm currently studying computer science, but have a background in electronics, prototyping, mechanical design, etc.  I am working with a local artist on a robot-themed kinetic sculpture project.  We initially intended to buy an original or replica split-flap from decades past, but the ones that we could find were out of our budget.  Our design team then stumbled upon your project page and we plan to use your modules.  We want to have 9 modules so that a 9 character word can be displayed.  But, I have a few questions about how things actually work with your existing code....

1) are both the python files and the arduino ino files required for a module to properly run?  Did you make a version of the code that involves just Arduino code controlling the module???

2) We'd like to avoid having to have a computer (or single board computer), and a custom motor driver pcb and would like to run an individual module using only an Arduino Nano and a motor driver pcb such as a ULN2003.  Is there a version of your arduino code that can run this?

Do you have an email address to converse further?

**Comment by scottbez1** [comment]
Catching up on old issues now - sorry for the really late response.

1) I haven't set up a standalone arduino example yet, but it should be doable. You would just need to modify the program to contain the messages you want to display and then call modules[i].GoToFlapIndex for each module when you want to set it to a particular message.

2) I haven't used an Arduino Nano, but there is support for using the ULN2003 drivers on an Uno - https://github.com/scottbez1/splitflap/wiki/Electronics#basic-prototyping-alternative-electronics-approach  This could likely be converted to work on an Arduino Nano, but may require making some adjustments to pinouts for the Nano rather than Uno.

My email is my github username at gmail.com - always happy to chat more!
