### ISSUE TITLE
neopixels are hard to solder?

### ISSUE THREAD

**Issue by kedarv** [scottbez1/splitflap#77]
I can't tell if this is me being inexperienced at soldering - but I found the neopixel units difficult to get soldered on the board securely. I managed to get most of them soldered on, but sometimes the contact becomes loose and they don't light up (or light up incorrectly).

I ended up resorting to printing out the neopixel light states to serial, but I'm wondering _why_ neopixel leds were used over conventional leds.

**Comment by scottbez1** [comment]
Yeah, the surface mount neopixels can be tricky to solder by hand unfortunately. I went with the neopixels because I wanted RGB for each channel to be able to show different statuses at a glance, and the led control needed to be chainable to support up to 12 LEDs since that's the max number of modules a single Arduino can control; neopixels handle both if those without requiring any additional ICs. It looks like there are 5mm through-hole neopixels available, so that might be an option for a future iteration.
