### ISSUE TITLE
Motors 1 and 3 are "bridged"?

### ISSUE THREAD

**Issue by kedarv** [scottbez1/splitflap#78]
I noticed while building four modules with `NUM_MODULES = 1` but with all four modules plugged in that module 3 would operate (along with 1, as expected) as though it was module 1. But when all four are plugged in, things appear to work correctly.

Curious if anyone has run into this, I'm unsure if this is a software issue or an issue with my controller board.

**Comment by scottbez1** [comment]
Sorry for the really late response here. This is more or less "expected" behavior if you have more motors plugged in than configured in the software, though the reason it's "expected" is a bit subtle:

What's happening is that each motor uses 4 outputs, and on the driver board there are 2 8-bit shift registers to output the necessary 16-bits for controlling all 4 motors. When NUM_MODULES is set to 1, the code will shift out 8 bits of data (4 bits for module 1, and 4 zero bits since you have to shift a full byte at a time even if we really only need 4 bits) before latching the shift registers. This means that the next time the code updates the motors, will will shift out another 8 bits before latching - this means that the previous 8 bits will get shifted to the second shift register (which controls motors 3 & 4) and latched, so the previous output for module 1's motor will now appear on the output for motor 3. This will continue happening (with motor 3 always 1 step behind motor 1) as output data continues to be shifted and latched.

So just make sure NUM_MODULES is at least as large as the number of motors your have plugged in.
